version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8082:8082"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  ai-data:
    build:
      context: ./ai-data
    container_name: ai-data
    ports:
      - "8000:8000"
    networks:
      - app-network

  ai-audio:
    build:
      context: ./ai-audio
    container_name: ai-audio
    ports:
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

