version: '3.8'

services:
  backend:
    container_name: backend
    image: backend:latest
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always

  ai-audio:
    container_name: ai-audio
    image: ai-audio:latest
    build:
      context: ./ai-audio
    ports:
      - "8001:8001"
    restart: always

  ai-data:
    container_name: ai-data
    image: ai-data:latest
    build:
      context: ./ai-data
    ports:
      - "8002:8002"
    restart: always

  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  jenkins_home:

